[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robo_manip_baselines"
description = "Software that integrates various imitation learning methods and benchmark task environments to provide baselines for robot manipulation"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
"ipython",
"gymnasium==1.0.0",
"mujoco==3.1.6",
"matplotlib>=3.3.4",
"imageio >=2.14.1",
"tqdm",
"opencv-python",
"pin",
"pyspacemouse",
]
dynamic = ["version"]

[project.optional-dependencies]
act = [
"torch",
"torchvision",
"pyquaternion",
"pyyaml",
"packaging",
"h5py",
]

[tool.setuptools.packages.find]
include = ["robo_manip_baselines", "robo_manip_baselines.*"]
